/** @typedef {{ ko: string, ja: string, jaReadings?: string[] }} WordEntry */

/** @type {WordEntry[]} */
export const WORD_ENTRIES = [
  { ko: '고양이', ja: '猫', jaReadings: ['ねこ'] },
  { ko: '강아지', ja: '犬', jaReadings: ['いぬ'] },
  { ko: '햄버거', ja: 'ハンバーガー' },
  { ko: '피자', ja: 'ピザ' },
  { ko: '비행기', ja: '飛行機', jaReadings: ['ひこうき'] },
  { ko: '자동차', ja: '車', jaReadings: ['くるま'] },
  { ko: '기타', ja: 'ギター' },
  { ko: '해변', ja: '海', jaReadings: ['うみ'] },
  { ko: '산', ja: '山', jaReadings: ['やま'] },
  { ko: '나무', ja: '木', jaReadings: ['き'] },
  { ko: '꽃', ja: '花', jaReadings: ['はな'] },
  { ko: '해', ja: '太陽', jaReadings: ['たいよう'] },
  { ko: '달', ja: '月', jaReadings: ['つき'] },
  { ko: '별', ja: '星', jaReadings: ['ほし'] },
  { ko: '우산', ja: '傘', jaReadings: ['かさ'] },
  { ko: '안경', ja: 'メガネ' },
  { ko: '시계', ja: '時計', jaReadings: ['とけい'] },
  { ko: '전화', ja: '電話', jaReadings: ['でんわ'] },
  { ko: '컴퓨터', ja: 'パソコン' },
  { ko: '책', ja: '本', jaReadings: ['ほん'] },
  { ko: '연필', ja: '鉛筆', jaReadings: ['えんぴつ'] },
  { ko: '가방', ja: 'かばん' },
  { ko: '신발', ja: '靴', jaReadings: ['くつ'] },
  { ko: '모자', ja: '帽子', jaReadings: ['ぼうし'] },
  { ko: '치킨', ja: 'チキン' },
  { ko: '라면', ja: 'ラーメン' },
  { ko: '김치', ja: 'キムチ' },
  { ko: '눈사람', ja: '雪だるま', jaReadings: ['ゆきだるま'] },
  { ko: '크리스마스', ja: 'クリスマス' },
  { ko: '할로윈', ja: 'ハロウィン' },
  { ko: '공룡', ja: '恐竜', jaReadings: ['きょうりゅう'] },
  { ko: '로봇', ja: 'ロボット' },
  { ko: '유령', ja: 'お化け', jaReadings: ['おばけ'] },
  { ko: '왕관', ja: '王冠', jaReadings: ['おうかん'] },
  { ko: '칼', ja: 'ナイフ' },
  { ko: '바나나', ja: 'バナナ' },
  { ko: '사과', ja: 'りんご' },
  { ko: '수박', ja: 'スイカ' },
  { ko: '딸기', ja: 'いちご' },
  { ko: '아이스크림', ja: 'アイスクリーム' },
  { ko: '케이크', ja: 'ケーキ' },
  { ko: '커피', ja: 'コーヒー' },
  { ko: '버스', ja: 'バス' },
  { ko: '기차', ja: '電車', jaReadings: ['でんしゃ'] },
  { ko: '배', ja: '船', jaReadings: ['ふね'] },
  { ko: '로켓', ja: 'ロケット' },
  { ko: '풍선', ja: '風船', jaReadings: ['ふうせん'] },
  { ko: '선글라스', ja: 'サングラス' },
  { ko: '마스크', ja: 'マスク' },
  { ko: '병원', ja: '病院', jaReadings: ['びょういん'] },
  { ko: '학교', ja: '学校', jaReadings: ['がっこう'] },
  { ko: '축구', ja: 'サッカー' },
  { ko: '농구', ja: 'バスケ' },
  { ko: '야구', ja: '野球', jaReadings: ['やきゅう'] },
  { ko: '테니스', ja: 'テニス' },
  { ko: '수영', ja: '水泳', jaReadings: ['すいえい'] },
  { ko: '낚시', ja: '釣り', jaReadings: ['つり'] },
  { ko: '캠핑', ja: 'キャンプ' },
  { ko: '텐트', ja: 'テント' },
  { ko: '피아노', ja: 'ピアノ' },
  { ko: '드럼', ja: 'ドラム' },
  { ko: '마이크', ja: 'マイク' },
  { ko: '카메라', ja: 'カメラ' },
  { ko: '텔레비전', ja: 'テレビ' },
  { ko: '냉장고', ja: '冷蔵庫', jaReadings: ['れいぞうこ'] },
  { ko: '세탁기', ja: '洗濯機', jaReadings: ['せんたくき'] },
  { ko: '침대', ja: 'ベッド' },
  { ko: '의자', ja: '椅子', jaReadings: ['いす'] },
  { ko: '책상', ja: '机', jaReadings: ['つくえ'] },
  { ko: '문', ja: 'ドア' },
  { ko: '창문', ja: '窓', jaReadings: ['まど'] },
  { ko: '계단', ja: '階段', jaReadings: ['かいだん'] },
  { ko: '엘리베이터', ja: 'エレベーター' },
  { ko: '화장실', ja: 'トイレ' },
  { ko: '거울', ja: '鏡', jaReadings: ['かがみ'] },
  { ko: '치약', ja: '歯磨き', jaReadings: ['はみがき'] },
  { ko: '칫솔', ja: '歯ブラシ' },
  { ko: '수건', ja: 'タオル' },
  { ko: '비누', ja: '石鹸', jaReadings: ['せっけん'] },
  { ko: '샤워', ja: 'シャワー' },
  { ko: '욕조', ja: '風呂', jaReadings: ['ふろ'] },
  { ko: '화분', ja: '植木鉢', jaReadings: ['うえきばち'] },
  { ko: '벌레', ja: '虫', jaReadings: ['むし'] },
  { ko: '나비', ja: '蝶', jaReadings: ['ちょう'] },
  { ko: '벌', ja: '蜂', jaReadings: ['はち'] },
  { ko: '개미', ja: '蟻', jaReadings: ['あり'] },
  { ko: '거미', ja: '蜘蛛', jaReadings: ['くも'] },
  { ko: '물고기', ja: '魚', jaReadings: ['さかな'] },
  { ko: '상어', ja: 'サメ' },
  { ko: '고래', ja: '鯨', jaReadings: ['くじら'] },
  { ko: '펭귄', ja: 'ペンギン' },
  { ko: '코끼리', ja: '象', jaReadings: ['ぞう'] },
  { ko: '기린', ja: 'キリン' },
  { ko: '사자', ja: 'ライオン' },
  { ko: '호랑이', ja: 'トラ' },
  { ko: '토끼', ja: 'うさぎ' },
  { ko: '햄스터', ja: 'ハムスター' },
  { ko: '앵무새', ja: 'オウム' },
  { ko: '독수리', ja: '鷲', jaReadings: ['わし'] },
  { ko: '번개', ja: '雷', jaReadings: ['かみなり'] },
  { ko: '비', ja: '雨', jaReadings: ['あめ'] },
  { ko: '눈', ja: '雪', jaReadings: ['ゆき'] },
  { ko: '구름', ja: '雲', jaReadings: ['くも'] },
  { ko: '무지개', ja: '虹', jaReadings: ['にじ'] },
  { ko: '태풍', ja: '台風', jaReadings: ['たいふう'] },
  { ko: '지진', ja: '地震', jaReadings: ['じしん'] },
  { ko: '초밥', ja: '寿司', jaReadings: ['すし'] },
  { ko: '도넛', ja: 'ドーナツ' },
  { ko: '초콜릿', ja: 'チョコ' },
  { ko: '빵', ja: 'パン' },
  { ko: '우유', ja: '牛乳', jaReadings: ['ぎゅうにゅう'] },
  { ko: '주스', ja: 'ジュース' },
  { ko: '만두', ja: '餃子', jaReadings: ['ぎょうざ'] },
  { ko: '포도', ja: 'ぶどう' },
  { ko: '복숭아', ja: '桃', jaReadings: ['もも'] },
  { ko: '당근', ja: 'にんじん' },
  { ko: '버섯', ja: 'きのこ' },
  { ko: '감자', ja: 'じゃがいも' },
  { ko: '토마토', ja: 'トマト' },
  { ko: '돼지', ja: '豚', jaReadings: ['ぶた'] },
  { ko: '소', ja: '牛', jaReadings: ['うし'] },
  { ko: '닭', ja: '鶏', jaReadings: ['にわとり'] },
  { ko: '말', ja: '馬', jaReadings: ['うま'] },
  { ko: '곰', ja: '熊', jaReadings: ['くま'] },
  { ko: '팬더', ja: 'パンダ' },
  { ko: '원숭이', ja: '猿', jaReadings: ['さる'] },
  { ko: '여우', ja: 'キツネ' },
  { ko: '늑대', ja: 'オオカミ' },
  { ko: '다람쥐', ja: 'リス' },
  { ko: '뱀', ja: 'ヘビ' },
  { ko: '개구리', ja: 'カエル' },
  { ko: '거북이', ja: '亀', jaReadings: ['かめ'] },
  { ko: '문어', ja: 'タコ' },
  { ko: '오징어', ja: 'イカ' },
  { ko: '게', ja: '蟹', jaReadings: ['かに'] },
  { ko: '새우', ja: 'エビ' },
  { ko: '돌고래', ja: 'イルカ' },
  { ko: '해파리', ja: 'クラゲ' },
  { ko: '자전거', ja: '自転車', jaReadings: ['じてんしゃ'] },
  { ko: '오토바이', ja: 'バイク' },
  { ko: '지하철', ja: '地下鉄', jaReadings: ['ちかてつ'] },
  { ko: '택시', ja: 'タクシー' },
  { ko: '헬리콥터', ja: 'ヘリコプター' },
  { ko: '우주선', ja: '宇宙船', jaReadings: ['うちゅうせん'] },
  { ko: '등대', ja: '灯台', jaReadings: ['とうだい'] },
  { ko: '다리', ja: '橋', jaReadings: ['はし'] },
  { ko: '터널', ja: 'トンネル' },
  { ko: '신호등', ja: '信号', jaReadings: ['しんごう'] },
  { ko: '집', ja: '家', jaReadings: ['いえ'] },
  { ko: '성', ja: '城', jaReadings: ['しろ'] },
  { ko: '편의점', ja: 'コンビニ' },
  { ko: '공원', ja: '公園', jaReadings: ['こうえん'] },
  { ko: '놀이터', ja: '遊び場', jaReadings: ['あそびば'] },
  { ko: '수족관', ja: '水族館', jaReadings: ['すいぞくかん'] },
  { ko: '도서관', ja: '図書館', jaReadings: ['としょかん'] },
  { ko: '전자레인지', ja: '電子レンジ', jaReadings: ['でんしれんじ'] },
  { ko: '에어컨', ja: 'エアコン' },
  { ko: '선풍기', ja: '扇風機', jaReadings: ['せんぷうき'] },
  { ko: '베개', ja: '枕', jaReadings: ['まくら'] },
  { ko: '이불', ja: '布団', jaReadings: ['ふとん'] },
  { ko: '열쇠', ja: '鍵', jaReadings: ['かぎ'] },
  { ko: '지갑', ja: '財布', jaReadings: ['さいふ'] },
  { ko: '가위', ja: 'はさみ' },
  { ko: '빗', ja: 'くし' },
  { ko: '망치', ja: 'ハンマー' },
  { ko: '손전등', ja: '懐中電灯', jaReadings: ['かいちゅうでんとう'] },
  { ko: '망원경', ja: '望遠鏡', jaReadings: ['ぼうえんきょう'] },
  { ko: '지구본', ja: '地球儀', jaReadings: ['ちきゅうぎ'] },
  { ko: '선물', ja: 'プレゼント' },
  { ko: '불꽃놀이', ja: '花火', jaReadings: ['はなび'] },
  { ko: '촛불', ja: 'ろうそく' },
  { ko: '호수', ja: '湖', jaReadings: ['みずうみ'] },
  { ko: '강', ja: '川', jaReadings: ['かわ'] },
  { ko: '폭포', ja: '滝', jaReadings: ['たき'] },
  { ko: '섬', ja: '島', jaReadings: ['しま'] },
  { ko: '화산', ja: '火山', jaReadings: ['かざん'] },
  { ko: '선인장', ja: 'サボテン' },
  { ko: '소방관', ja: '消防士', jaReadings: ['しょうぼうし'] },
  { ko: '경찰', ja: '警察', jaReadings: ['けいさつ'] },
  { ko: '의사', ja: '医者', jaReadings: ['いしゃ'] },
  { ko: '해적', ja: '海賊', jaReadings: ['かいぞく'] },
  { ko: '닌자', ja: '忍者', jaReadings: ['にんじゃ'] },
  { ko: '외계인', ja: '宇宙人', jaReadings: ['うちゅうじん'] },
  { ko: '산타클로스', ja: 'サンタ' },
  { ko: '배구', ja: 'バレー' },
  { ko: '골프', ja: 'ゴルフ' },
  { ko: '스키', ja: 'スキー' },
  { ko: '볼링', ja: 'ボウリング' },
  { ko: '미끄럼틀', ja: '滑り台', jaReadings: ['すべりだい'] },
  { ko: '그네', ja: 'ブランコ' },
  { ko: '곰인형', ja: 'テディベア' },
  { ko: '인형', ja: '人形', jaReadings: ['にんぎょう'] },
  { ko: '주사위', ja: 'サイコロ' },
  { ko: '보물상자', ja: '宝箱', jaReadings: ['たからばこ'] },
  { ko: '다이아몬드', ja: 'ダイヤ' },
  { ko: '반지', ja: '指輪', jaReadings: ['ゆびわ'] },
  { ko: '목걸이', ja: 'ネックレス' },
  { ko: '우체국', ja: '郵便局', jaReadings: ['ゆうびんきょく'] },
  { ko: '편지', ja: '手紙', jaReadings: ['てがみ'] },
  { ko: '사진', ja: '写真', jaReadings: ['しゃしん'] },
  { ko: '노래', ja: '歌', jaReadings: ['うた'] },
  { ko: '춤', ja: 'ダンス' },
];
